name: 'build-test'
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          npm install
      - run: |
          npm run all
  test-add:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          users: gateixeira-ghost
          repositories: gateixeira-demos/test1
          role: read
          action: add

  test-remove:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          users: gateixeira-ghost
          repositories: gateixeira-demos/test1
          role:
          action: remove
