name: 'build-test'
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          npm install
      - run: |
          npm run all
  test-add:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Retrieve the admin token
        id: github-app
        uses: getsentry/action-github-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - uses: ./
        with:
          token: ${{ steps.github-app.outputs.token }}
          users: gateixeira-ghost
          repositories: gateixeira-demos/test1
          role: read
          action: add

  test-remove:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Retrieve the admin token
        id: github-app
        uses: getsentry/action-github-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - uses: ./
        with:
          token: ${{ steps.github-app.outputs.token }}
          users: gateixeira-ghost
          repositories: gateixeira-demos/test1
          role:
          action: remove
